SELECT HISTORY_ID, 
    round(DAILY_FEE * (DATEDIFF(b.END_DATE,b.START_DATE)+1)
    * (case 
    when DATEDIFF(END_DATE,START_DATE)+1 < 7 then 1
    when DATEDIFF(END_DATE,START_DATE)+1 < 30 then 0.95
    when DATEDIFF(END_DATE,START_DATE)+1 < 90 then 0.92
    else 0.85 end)) as "FEE"
FROM CAR_RENTAL_COMPANY_CAR a
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b
    ON a.CAR_ID = b.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN c
    ON a.CAR_TYPE = c.CAR_TYPE
WHERE a.CAR_TYPE = '트럭'
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC
