-- 코드를 입력하세요
SELECT f.USER_ID, f.NICKNAME, SUM(b.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD b
    JOIN USED_GOODS_USER f
    ON b.WRITER_ID = f.USER_ID
WHERE b.STATUS = 'DONE'
GROUP BY b.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES